### ISSUE TITLE
TOP66 - Low pressure

### ISSUE THREAD

**Issue by nofeardh** [heishamon/HeishaMon#232]
Hi,

Does anyone knows what exactly is TOP66 (low pressure) - on mine HeishaMon page It's allways 0 kgf/cm2. 

Kind regards,
Aljosa

**Comment by MiG-41** [comment]
Hi , this value is assumed based on experience with Service Cloud . We havn't found a HP , with shows this value , but we can't be sure , since in Srvice Cloud such "TOP" also exist (and it is 0 all the time as well) , and we can't check all HP , so if somone find in TOP66 other value then 0 , please share with model , and results.

EDIT: Or if in Service Cloud he have some readings of Low Pressure ( other then 0 ) , but TOP66 gives 0....
