### ISSUE TITLE
WH-SQC12H9E8 External Control Contact

### ISSUE THREAD

**Issue by BlueCase** [heishamon/HeishaMon#450]
Hi,
is it possible to get the state about the external contact switch?

**Comment by MiG-41** [comment]
Yes,  in byte 110 bit7&8 givess actual status , you could extract it from topic panasonic_heat_pump/raw/data
If you want to have it as one of TOPs , maybe @IgorYbema will add it...

**Comment by BlueCase** [comment]
@IgorYbema would that possible?

**Comment by BlueCase** [comment]
@MiG-41 Do you know or have an example how to get this working with homeassistent?

**Comment by MiG-41** [comment]
I can give you simple flow for NodeRED.
..

**Comment by BlueCase** [comment]
@MiG-41 sorry for the lat reply but I had other topics with more priority :). thanks for the offer. can you provide the flow?
@IgorYbema Any Update. Would it possible to add?

**Comment by MiG-41** [comment]
Somethink like this:

[{"id":"3fb91e04a87c11b7","type":"mqtt in","z":"29ae07782cca960c","name":"","topic":"panasonic_heat_pump/raw/data","qos":"2","datatype":"auto","broker":"70855f4b.303b1","nl":false,"rap":false,"inputs":0,"x":190,"y":180,"wires":[["0dd4a9e922de38b0","49b0545a45cc3209"]]},{"id":"0dd4a9e922de38b0","type":"function","z":"29ae07782cca960c","name":"110","func":"\nmsg.payload = Number((msg.payload[110] & 0b11111111) >> 7 );\n\nreturn msg ;","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":410,"y":180,"wires":[["fd839e51f775cad0"]]},{"id":"fd839e51f775cad0","type":"mqtt out","z":"29ae07782cca960c","name":"","topic":"panasonic_heat_pump/raw/External switch","qos":"","retain":"false","respTopic":"","contentType":"","userProps":"","correl":"","expiry":"","broker":"70855f4b.303b1","x":670,"y":180,"wires":[]},{"id":"49b0545a45cc3209","type":"function","z":"29ae07782cca960c","name":"110","func":"\nmsg.payload = Number((msg.payload[110] & 0b00111111) >> 5 );\n\nreturn msg ;","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":410,"y":240,"wires":[["97609334b7603dc8"]]},{"id":"97609334b7603dc8","type":"mqtt out","z":"29ae07782cca960c","name":"","topic":"panasonic_heat_pump/raw/CoolHeat","qos":"","retain":"false","respTopic":"","contentType":"","userProps":"","correl":"","expiry":"","broker":"70855f4b.303b1","x":650,"y":240,"wires":[]},{"id":"70855f4b.303b1","type":"mqtt-broker","name":"","broker":"192.168.1.90","port":"1883","clientid":"","autoConnect":true,"usetls":false,"verifyservercert":true,"protocolVersion":"4","keepalive":"15","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","birthMsg":{},"closeTopic":"","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willPayload":"","willMsg":{},"userProps":"","sessionExpiry":""}]

Import it to node red. It will read topic panasonic_heat_pump/raw/data ( so you need to Enable in Heishamon settings "Debug log to MQTT topic from start" ) , and it will set give a result in topic panasonic_heat_pump/raw/External switch (and also for edu purpose panasonic_heat_pump/raw/CoolHeat )....

BTW , this Bit for Cool Heat Switch may be not true , since it gives me no results when Cooling... So please veryfy if , External Switch gives proper results....

**Comment by BlueCase** [comment]
@MiG-41 Thanks for your help. Will try it :)
