### ISSUE TITLE
Are optional pcb commands sent continously?

### ISSUE THREAD

**Issue by HighlyCompressedAir** [heishamon/HeishaMon#536]
I'm building a new ruleset that relies heavily on optional pcb commands like @SetSmartGridMode and @SetZ2RoomTemp. Since normal commands can be lost sometimes and therefore not executed, I wonder if it's the same with those or are they're being sent continously like other optional pcb data? I need to know if I have to put them on a looping timer or not.

**Comment by geduxas** [comment]
All record's on pcb emulation should be sent to pump continuesly . There is no set once and forget. So yes, to be in safe side you should update them.

**Comment by IgorYbema** [comment]
Not exactly right. If received by heishamon (lets assume it is received), it will update the internal data query to the heatpump (optional data query). The responding byte in the query is changed to have that value. As long as heishamon is running that will be kept in memory and doesn't need to be updated (if value didn't change).
And if you used MQTT and with retained flag, it will also be reboot save as heishamon wil reread that after reconnecting to MQTT after the reboot. Only when you use the internal rules or the url set command, you should need to resend it after reboot.

This works indeed a bit different than the normal topics which is only send once, if received. And therefore should be checked for change at the automation software side. This is because the data query is build differently. This is how the heatpump works.
